[phases.setup]
aptPkgs = ['...','build-essential','gettext','python3-dev', 'zlib1g-dev', 'libpq-dev', 'libtiff5-dev','libjpeg62-turbo-dev','libfreetype6-dev','liblcms2-dev','libwebp-dev']


[phases.install]
nixPkgs = ['...', 'uv']
cmds=[]

[phases.build]
cmds = ['uv add -r requirements/production.txt','uv run manage.py collectstatic --noinput', 'uv run manage.py migrate']

[start]
cmd = 'gunicorn config:wsgi'
